/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "gcd.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

gcdout *
gcd_1(gcdin *argp, CLIENT *clnt)
{
	static gcdout clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, GCD,
		(xdrproc_t) xdr_gcdin, (caddr_t) argp,
		(xdrproc_t) xdr_gcdout, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
