/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "gcd.h"

bool_t
xdr_gcdin (XDR *xdrs, gcdin *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->x))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->y))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_gcdout (XDR *xdrs, gcdout *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->z))
		 return FALSE;
	return TRUE;
}
