/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "gcd.h"

int gcd(m,n){
	if(n == 0){
		return m;
	}
	else{
		return gcd(n, m%n);		
	}
}

gcdout *
gcd_1_svc(gcdin *argp, struct svc_req *rqstp)
{
	static gcdout  result;
	
	/*
	 * insert server code here
	 */
	result.z = gcd(argp->x, argp->y);

	return &result;
}
