/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calc.h"

float *
calc_1_svc(calc_in *argp, struct svc_req *rqstp)
{
	static float  result;

	/*
	 * insert server code here
	 */
	 printf("%d", argp->z);
	 if(argp->z == 1){
	 	result = argp->x + argp->y;}
 	 else if(argp->z == 2){
	 	result = argp->x - argp->y;}
	 else if(argp->z==3){
	 	result = argp->x * argp->y;}
	 else if(argp->z == 4){
	 	result = argp->x / argp->y;}
	 

	return &result;
}
