/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calc.h"


void
calc_p_1(char *host, int x,int y,int z)
{
	CLIENT *clnt;
	float  *result_1;
	calc_in  calc_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, CALC_P, CALC_V, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
    calc_1_arg.x=x;
    calc_1_arg.y=y;
    calc_1_arg.z=z;
	result_1 = calc_1(&calc_1_arg, clnt);
	if (result_1 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else{
		printf("result: %f\n", *result_1);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 5) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	
	calc_p_1 (host, atoi(argv[2]),atoi(argv[3]),atoi(argv[4]));
exit (0);
}
